---
- name: Wipe application
  tags: never
  when: web_app_full_wipe|bool
  block:
    - name: Stop and Delete the container
      community.docker.docker_container:
        name: "{{ app_container_name }}"
        # Stops the container and after that removes it
        state: absent

- name: Wipe application using Docker Compose
  tags: web_app_wipe
  when: web_app_full_wipe|bool
  block:
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: docker-compose.yml
        state: absent
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output