---
- name: Wipe application
  tags: web_app_wipe
  when: web_app_full_wipe|bool
  block:
    - name: Stop and Delete the container
      community.docker.docker_container:
        name: "{{ app_container_name }}"
        # Stops the container and after that removes it
        state: absent