version: "3"

networks:
  monitoring:

services:
  app_python:
    image: yesliesnayder/app_python:1.0.3
    ports:
      - "8000:8000"

    logging: &logging
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  app_golang:
    image: yesliesnayder/webservicego:0.0.2
    ports:
      - "8001:8000"
    logging:
      <<: *logging

  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    logging:
      <<: *logging

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - monitoring
    logging:
      <<: *logging

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    image: grafana/grafana:10.1.5
    volumes:
      - ./grafana:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - monitoring
    logging:
      <<: *logging

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./prometheus:/etc/prometheus
    command: '--config.file=/etc/prometheus/config.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    logging:
      <<: *logging
