- name: Deploy App Python
  hosts: all
  become: true
  roles:
    - role: web_app
      vars:
        app_container_name: app_python
        app_container_image: "yesliesnayder/app_python:1.0.3"
        app_container_ports:
          - "8000:8000"